### ISSUE TITLE
Embedded demo is broken right now

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse.js#1133]
See: https://conversejs.org/demo/embedded.html

I guess related to the refactor of the embedded chat.

Any idea when this will be finished?

I would like to update the HubZilla plugin that uses an ancient version of ConverseJS and the plan is to include the embedded chat, thus it would be nice to hear how to do it best with the new system.
https://framagit.org/hubzilla/addons/tree/master/xmpp

**Comment by jcbrand** [comment]
We're planning the 4.0.0 release for some time in August, by then this should also be up to date and fixed.

**Comment by poVoq** [comment]
Functions again. Great work on version 4.0!

**Comment by jcbrand** [comment]
Thanks 😀

**Comment by Lynesth** [comment]
Hey there.

Sorry to bump this issue @jcbrand but the embedded demo is not working and I'm getting the same error if I set `view_mode: 'embedded'` in my own code (using 4.0.4).

According to chrome:

```
FATAL: TypeError: Cannot read property 'extend' of undefined
at Object.initialize (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:155:494290)
at o.initializePlugin (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:153:211308)
at Jt (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:91:5240)
at Object.Us (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:91:40290)
at o.initializePlugins (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:153:211881)
at Object.initPlugins (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:153:239074)
at o (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:153:224070)
at https://cdn.conversejs.org/4.0.4/dist/converse.min.js:83:2943
at C (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:83:2977)
at E (https://cdn.conversejs.org/4.0.4/dist/converse.min.js:83:2798)
```

Regards.

**Comment by jcbrand** [comment]
@Lynesth It's already fixed in this commit: https://github.com/conversejs/converse.js/commit/f974c79acf70c6c920be79cc6f9f29ecdece3850

The next release will contain that fix, and probably only then will  the demo work again as well.
