### ISSUE TITLE
FATAL: Error: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.

### ISSUE THREAD

**Issue by ozanuzer** [conversejs/converse.js#1244]
Hello,

When I use converse js on my panel, that error occur;

FATAL: Error: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.    at child._ensureElement (http://localhost.com/conversejs/converse.js:61351:32)    at child.Backbone.View (http://localhost.com/conversejs/converse.js:3822:10)    at child.constructor (http://localhost.com/conversejs/converse.js:2075:21)    at child.Backbone.Overview (http://localhost.com/conversejs/converse.js:2365:14)    at new child (http://localhost.com/conversejs/converse.js:4483:41)    at Object._converse.api.listen.on (http://localhost.com/conversejs/converse.js:61424:34)    at triggerEvents (http://localhost.com/conversejs/converse.js:2967:57)    at triggerApi (http://localhost.com/conversejs/converse.js:2955:19)    at eventsApi (http://localhost.com/conversejs/converse.js:2754:16)    at Object.Events.trigger (http://localhost.com/conversejs/converse.js:2945:5)

Anyone can help me?

**Comment by ozanuzer** [comment]
I changed location of code, now working. I think conflicting some other codes.
