### ISSUE TITLE
Websocket Error: A "url" property or function must be specified

### ISSUE THREAD

**Issue by JuliaBonita** [conversejs/converse.js#1698]
**Describe the bug**

The Converse.js client works fine with BOSH, but when I switch to websockets (by enabling and specifying the `websocket_url`), the connection works for a short time, but then `Error: A "url" property or function must be specified` appears in the JS console after 60 seconds of inactivity. After this error appears, the clients lose their connection to the server and their chats do not get delivered to chat participants.

I've enabled:
```
auto_reconnect: true,
keepalive: true
```
But they don't resolve the problem.

**Environment:**
I'm just using the example web client loaded from the Converse.js CDN website (https://cdn.conversejs.org/5.0.1/dist/converse.min.css)
 - Problem occurs on all browsers.
 - Converse.js version: 5.0.1
- XMPP Server: eJabberd (latest version) with default settings. (BOSH and Websockets are enabled by default.)

Websockets are much more resource-efficient than BOSH, so I would really like to implement the websocket version. Please help.

**Comment by jcbrand** [comment]
The error `Error: A "url" property or function must be specified` is very generic and doesn't really provide any useful information as to what's going wrong.

I'm using Converse with websocket since about 2 months now, so it does work generally.

Please set `debug` to `true` when calling `converse.initialize` and then check if you see any other errors or relevant output in your browser console (hint: you also need to set logging to `verbose` in the browser console).

**Comment by JuliaBonita** [comment]
Thank you for your reply. 

The debugging output shows that the messages are being received as expected, but after the 60 seconds of inactivity, they simply stop appearing in the GUI. Even though both sides of the connection are receiving the XMPP stanzas in their respective consoles, the messages still don't appear in the GUI. The only thing that appears in the chat box is "julia@localhost has gone offline". Then, I have to refresh the browser and login again to see any more messages.  

There's another similar warning in the console: `WARNING: Removing Strophe handlers due to uncaught exception: A "url" property or function must be specified`.

Here's the associated debugging output when the error initially occurs:

```
converse-core.js:288  FATAL: Error: A "url" property or function must be specified    at Y (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:29969)    at o.url (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:13485)    at Function.ho.result (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:9:61535)    at o.t.sync (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:23378)    at o.e.sync (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:1:4375)    at o.sync (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:10581)    at o.save (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:13031)    at onResourcesChanged (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:151:510918)    at m (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:9357)    at h (https://cdn.conversejs.org/5.0.1/dist/converse.min.js:62:9091)
Pe.log @ converse-core.js:288
Ne.log @ converse-core.js:668
fatal @ core.js:868
_handleError @ core.js:770
run @ core.js:1310
(anonymous) @ core.js:2549
forEachChild @ core.js:306
_dataRecv @ core.js:2538
_onMessage @ websocket.js:499
converse-core.js:288  FATAL: error: A "url" property or function must be specified
Pe.log @ converse-core.js:288
Ne.log @ converse-core.js:668
fatal @ core.js:868
_handleError @ core.js:780
run @ core.js:1310
(anonymous) @ core.js:2549
forEachChild @ core.js:306
_dataRecv @ core.js:2538
_onMessage @ websocket.js:499
converse-core.js:286  2019-09-03T05:57:43.660Z WARNING: Removing Strophe handlers due to uncaught exception: A "url" property or function must be specified 
Pe.log @ converse-core.js:286
Ne.log @ converse-core.js:668
warn @ core.js:848
(anonymous) @ core.js:2557
forEachChild @ core.js:306
_dataRecv @ core.js:2538
_onMessage @ websocket.js:499
converse-core.js:291  2019-09-03T05:57:44.373Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T05:57:44.374Z DEBUG: <presence xmlns="jabber:client" from="julia@localhost/converse.js-96069450" to="sally@localhost/converse.js-25757106"><priority>0</priority><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://conversejs.org" ver="IrMymqGSRjPlGDbL6l/mQD9YKOk="/></presence>
converse-core.js:284  ERROR: Websocket closed unexpectedly
Pe.log @ converse-core.js:284
Ne.error @ converse-core.js:299
_onClose @ websocket.js:352
converse-core.js:291  2019-09-03T05:57:52.941Z DEBUG: _doDisconnect was called 
converse-core.js:291  2019-09-03T05:57:52.941Z DEBUG: WebSockets _doDisconnect was called 
converse-core.js:293  2019-09-03T05:57:52.941Z INFO: Status changed to: DISCONNECTED 
converse-core.js:293  2019-09-03T05:57:52.941Z INFO: RECONNECTING: the connection has dropped, attempting to reconnect. 
converse-core.js:293  2019-09-03T05:57:52.943Z INFO: Status changed to: CONNECTING 
converse-core.js:291  2019-09-03T05:57:53.092Z DEBUG: Websocket open 
converse-core.js:291  2019-09-03T05:57:53.093Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="localhost" version="1.0"/>
converse-core.js:291  2019-09-03T05:57:53.167Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" version="1.0" xml:lang="en" id="2C7F4CB089C422CE" from="localhost"/>
converse-core.js:291  2019-09-03T05:57:53.167Z DEBUG: _connect_cb was called 
converse-core.js:291  2019-09-03T05:57:53.168Z DEBUG: <features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></features>
```
Then it goes into the following loop:
```
ERROR: Websocket closed unexpectedly
Pe.log @ converse-core.js:284
Ne.error @ converse-core.js:299
_onClose @ websocket.js:352
converse-core.js:291  2019-09-03T06:15:58.902Z DEBUG: _doDisconnect was called 
converse-core.js:291  2019-09-03T06:15:58.902Z DEBUG: WebSockets _doDisconnect was called 
converse-core.js:293  2019-09-03T06:15:58.902Z INFO: Status changed to: DISCONNECTED 
converse-core.js:293  2019-09-03T06:15:58.902Z INFO: RECONNECTING: the connection has dropped, attempting to reconnect. 
converse-core.js:293  2019-09-03T06:15:58.904Z INFO: Status changed to: CONNECTING 
converse-core.js:291  2019-09-03T06:15:59.028Z DEBUG: Websocket open 
converse-core.js:291  2019-09-03T06:15:59.028Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="localhost" version="1.0"/>
converse-core.js:291  2019-09-03T06:15:59.089Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" version="1.0" xml:lang="en" id="D314A9C455DEA77B" from="localhost"/>
converse-core.js:291  2019-09-03T06:15:59.089Z DEBUG: _connect_cb was called 
converse-core.js:291  2019-09-03T06:15:59.089Z DEBUG: <features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></features>
converse-core.js:291  2019-09-03T06:15:59.090Z DEBUG: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1mZXJyaXMscj03YTBjN2NjNWNjNDkxMGFhZGZjMjQ5NDUwMDFiNjk1Yg==</auth>
converse-core.js:291  2019-09-03T06:15:59.167Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.167Z DEBUG: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj03YTBjN2NjNWNjNDkxMGFhZGZjMjQ5NDUwMDFiNjk1YkVWbVJLa2dLSi9qSzg0WWI2WW9Bdnc9PSxzPVcybzlOZ2JPYVBCTDVZUTl0MXFKdUE9PSxpPTQwOTY=</challenge>
converse-core.js:291  2019-09-03T06:15:59.201Z DEBUG: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1iaXdzLHI9N2EwYzdjYzVjYzQ5MTBhYWRmYzI0OTQ1MDAxYjY5NWJFVm1SS2tnS0ovaks4NFliNllvQXZ3PT0scD1zamw1WVdsREpZcXdUUzIvbHdmRlg0RlVPUkU9</response>
converse-core.js:291  2019-09-03T06:15:59.263Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.263Z DEBUG: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">dj05VzlkblFKc2RrYUd2UVBCL29MR0RuSWJ4dm89</success>
converse-core.js:293  2019-09-03T06:15:59.263Z INFO: SASL authentication succeeded. 
converse-core.js:291  2019-09-03T06:15:59.264Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="localhost" version="1.0"/>
converse-core.js:291  2019-09-03T06:15:59.325Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.326Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" version="1.0" xml:lang="en" id="192B7EFC3CBB2490" from="localhost"/>
converse-core.js:291  2019-09-03T06:15:59.326Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.326Z DEBUG: <features xmlns="http://etherx.jabber.org/streams"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/><register xmlns="http://jabber.org/features/iq-register"/><sm xmlns="urn:xmpp:sm:3"/></features>
converse-core.js:293  2019-09-03T06:15:59.326Z INFO: Status changed to: undefined 
converse-core.js:291  2019-09-03T06:15:59.328Z DEBUG: <iq type="set" id="_bind_auth_2" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>converse.js-25757106</resource></bind></iq>
converse-core.js:291  2019-09-03T06:15:59.391Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.392Z DEBUG: <iq xmlns="jabber:client" id="_bind_auth_2" type="result"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>sally@localhost/converse.js-25757106</jid></bind></iq>
converse-core.js:291  2019-09-03T06:15:59.392Z DEBUG: <iq type="set" id="_session_auth_2" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>
converse-core.js:291  2019-09-03T06:15:59.454Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.454Z DEBUG: <iq xmlns="jabber:client" type="result" id="_session_auth_2"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>
converse-core.js:293  2019-09-03T06:15:59.454Z INFO: Status changed to: CONNECTED 
converse-core.js:293  2019-09-03T06:15:59.454Z INFO: Reconnected 
converse-core.js:291  2019-09-03T06:15:59.458Z DEBUG: <iq type="get" id="ff460c6f-ad4e-4ddf-a03c-843d7f5b9621:roster" xmlns="jabber:client"><query xmlns="jabber:iq:roster"/></iq>
converse-core.js:291  2019-09-03T06:15:59.524Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.524Z DEBUG: <iq xmlns="jabber:client" from="sally@localhost" to="sally@localhost/converse.js-25757106" id="ff460c6f-ad4e-4ddf-a03c-843d7f5b9621:roster" type="result"><query xmlns="jabber:iq:roster"><item subscription="both" jid="julia@localhost"/></query></iq>
converse-core.js:291  2019-09-03T06:15:59.533Z DEBUG: <presence xmlns="jabber:client"><priority>0</priority><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://conversejs.org" ver="IrMymqGSRjPlGDbL6l/mQD9YKOk="/></presence>
converse-core.js:291  2019-09-03T06:15:59.600Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.600Z DEBUG: <presence xmlns="jabber:client" from="sally@localhost/converse.js-25757106" to="sally@localhost/converse.js-25757106"><priority>0</priority><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://conversejs.org" ver="IrMymqGSRjPlGDbL6l/mQD9YKOk="/></presence>
converse-core.js:291  2019-09-03T06:15:59.600Z DEBUG: _dataRecv called 
converse-core.js:291  2019-09-03T06:15:59.601Z DEBUG: <presence xmlns="jabber:client" from="julia@localhost/converse.js-2098685" to="sally@localhost/converse.js-25757106"><priority>0</priority><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://conversejs.org" ver="IrMymqGSRjPlGDbL6l/mQD9YKOk="/><delay xmlns="urn:xmpp:delay" stamp="2019-09-03T06:05:34Z" from="julia@localhost/converse.js-2098685"/></presence>
```

When it's in that loop, I can send messages and they appear in the console log, but they don't appear in the chat box GUI. Weird.

**Comment by jcbrand** [comment]
> but after the 60 seconds of inactivity

The BOSH timeout is 60 seconds, which makes me wonder whether there is some weird interference between websocket and BOSH.

Does it work when you specify only the `websocket_url` and remove `bosh_service_url`?

What does your `converse.initialize` call look like?

**Comment by JuliaBonita** [comment]
Hi, sorry for delayed reply. I've been traveling and am catching up on messages now.

`bosh_service_url` is not included in `converse.initialize`; so I don't think that's the problem.

I can see in the console that the messages are received on both sides. They're just not appearing in the GUI after the errors above start appearing around 60 seconds after login.

Here's what I have in `converse.initialize`:
```
debug: true,
      auto_reconnect: true,
      keepalive: true,
      view_mode: 'overlayed',
      websocket_url: 'ws://34.239.112.21:5280/ws-xmpp',
      show_send_button: true,
      ```

**Comment by jcbrand** [comment]
Sorry @JuliaBonita, I have no idea what might be causing this.

**Comment by joudinet** [comment]
Hi, this looks very similar to the problem I'm facing. I also use ejabberd as the XMPP server (version 18.09). I've activated debug log on both conversejs-5.0.1 and ejabberd-18.09 to try to understand why the websocket connection drops after few minutes and fails to reopen afterward.
Here conversejs's log when the problem occurs:
```
ERROR: Websocket closed unexpectedly converse.js:149:12388
    log https://testbed-1.gnyoi.com/conversejs/converse.js:149
    error https://testbed-1.gnyoi.com/conversejs/converse.js:149
    _onClose https://testbed-1.gnyoi.com/conversejs/converse.js:128
 2019-09-17T10:17:25.824Z DEBUG: _doDisconnect was called converse.js:149:12661
 2019-09-17T10:17:25.825Z DEBUG: WebSockets _doDisconnect was called converse.js:149:12661
 2019-09-17T10:17:25.825Z INFO: Status changed to: DISCONNECTED converse.js:149:12751
 2019-09-17T10:17:25.839Z DEBUG: <presence type="unavailable" from="5294718142784173736419@gnyoi.com/13016536059993931488435" to="forum@conference.gnyoi.com/Bob" id="6e1ea6c0-d1f7-4482-8144-6dfc093674c2:sendPresence"><status/></presence> converse.js:149:12661
 2019-09-17T10:17:25.840Z INFO: RECONNECTING: the connection has dropped, attempting to reconnect. converse.js:149:12751
 2019-09-17T10:17:25.848Z INFO: Status changed to: CONNECTING converse.js:149:12751
TypeError: this.socket is null
converse.js:128:234711
GET https://testbed-1.gnyoi.com/ws/
[HTTP/1.1 101 Switching Protocols 521ms]

 2019-09-17T10:17:26.925Z DEBUG: Websocket open converse.js:149:12661
 2019-09-17T10:17:26.925Z DEBUG: <open to="gnyoi.com" version="1.0"/> converse.js:149:12661
 2019-09-17T10:17:26.931Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" id="8486992899793807183" version="1.0" xml:lang="en" from="gnyoi.com"/> converse.js:149:12661
 2019-09-17T10:17:26.934Z DEBUG: _connect_cb was called converse.js:149:12661
 2019-09-17T10:17:26.934Z DEBUG: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/></stream:features> converse.js:149:12661
 2019-09-17T10:17:26.934Z DEBUG: <presence type="unavailable" from="5294718142784173736419@gnyoi.com/13016536059993931488435" to="forum@conference.gnyoi.com/Bob" id="6e1ea6c0-d1f7-4482-8144-6dfc093674c2:sendPresence"><status/></presence> converse.js:149:12661
 2019-09-17T10:17:26.935Z DEBUG: <auth mechanism="PLAIN">NTI5NDcxODE0Mjc4NDE3MzczNjQxOUBnbnlvaS5jb20ANTI5NDcxODE0Mjc4NDE3MzczNjQxOQBudWxs</auth> converse.js:149:12661
 ERROR: WebSocket stream error: not-authorized converse.js:149:12388
 2019-09-17T10:17:26.940Z INFO: Status changed to: ERROR converse.js:149:12751
 2019-09-17T10:17:26.941Z DEBUG: _doDisconnect was called converse.js:149:12661
 2019-09-17T10:17:26.941Z DEBUG: WebSockets _doDisconnect was called converse.js:149:12661
 2019-09-17T10:17:26.942Z INFO: Status changed to: DISCONNECTED converse.js:149:12751
 2019-09-17T10:17:26.948Z DEBUG: <presence type="unavailable" from="5294718142784173736419@gnyoi.com/13016536059993931488435" to="forum@conference.gnyoi.com/Bob" id="7e7c54e7-5bb8-4ec3-9b27-3e0e32a80f1d:sendPresence"><status/></presence> converse.js:149:12661
TypeError: this.socket is null
converse.js:128:234711
 2019-09-17T10:17:28.948Z INFO: RECONNECTING: the connection has dropped, attempting to reconnect. converse.js:149:12751
 2019-09-17T10:17:28.960Z INFO: Status changed to: CONNECTING converse.js:149:12751
GET https://testbed-1.gnyoi.com/ws/
[HTTP/1.1 101 Switching Protocols 515ms]

 2019-09-17T10:17:29.488Z DEBUG: Websocket open converse.js:149:12661
 2019-09-17T10:17:29.489Z DEBUG: <open to="gnyoi.com" version="1.0"/> converse.js:149:12661
 2019-09-17T10:17:29.498Z DEBUG: <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" id="13117055335665057913" version="1.0" xml:lang="en" from="gnyoi.com"/>
```

The server log at the same time (UTC+2):
```
2019-09-17 12:15:05.571 [debug] <0.763.0>@ejabberd_websocket:ws_loop:190 tcp connection was closed, exit
2019-09-17 12:15:05.574 [debug] <0.765.0>@mod_pubsub:node_action:3589 node_action <<"pubsub.gnyoi.com">> <<"flat">> get_entity_affiliations [<<"pubsub.gnyoi.com">>,{<<"75401492385954811991842">>,<<"gnyoi.com">>,<<"174824222595048155621858">>}]
2019-09-17 12:15:05.575 [debug] <0.765.0>@mod_pubsub:node_call:3570 node_call <<"flat">> get_entity_affiliations [<<"pubsub.gnyoi.com">>,{<<"75401492385954811991842">>,<<"gnyoi.com">>,<<"174824222595048155621858">>}]
2019-09-17 12:15:05.577 [debug] <0.765.0>@mod_pubsub:node_action:3589 node_action <<"pubsub.gnyoi.com">> <<"pep">> get_entity_affiliations [<<"pubsub.gnyoi.com">>,{<<"75401492385954811991842">>,<<"gnyoi.com">>,<<"174824222595048155621858">>}]
2019-09-17 12:15:05.582 [debug] <0.765.0>@mod_pubsub:node_call:3570 node_call <<"pep">> get_entity_affiliations [<<"pubsub.gnyoi.com">>,{<<"75401492385954811991842">>,<<"gnyoi.com">>,<<"174824222595048155621858">>}]
2019-09-17 12:15:05.584 [info] <0.765.0>@ejabberd_c2s:process_terminated:262 (websocket|<0.764.0>) Closing c2s session for 75401492385954811991842@gnyoi.com/174824222595048155621858: Connection failed: connection closed
2019-09-17 12:15:05.586 [debug] <0.765.0>@mod_carboncopy:disable:262 disabling for <<"75401492385954811991842">>
2019-09-17 12:15:05.592 [debug] <0.765.0>@mod_shared_roster:unset_presence:698 unset_presence for <<"75401492385954811991842">> @ <<"gnyoi.com">> / <<"174824222595048155621858">> -> <<"Connection failed: connection closed">> (0 resources)
2019-09-17 12:15:06.434 [info] <0.535.0>@ejabberd_listener:accept:221 (<0.784.0>) Accepted connection ::ffff:127.0.0.1:41142 -> ::ffff:127.0.0.1:5443
2019-09-17 12:15:06.465 [debug] <0.784.0>@ejabberd_http:process_header:304 ({tlssock,#Port<0.60>,#Ref<0.182672663.2372272129.221979>}) http query: 'GET' <<"/ws/">>
2019-09-17 12:15:06.465 [debug] <0.784.0>@ejabberd_http:process:391 [<<"ws">>] matches [<<"ws">>]
2019-09-17 12:15:06.467 [debug] <0.784.0>@ejabberd_websocket:connect:124 Sent handshake response : [<<"HTTP/1.1 101 Switching Protocols\r\n">>,<<"Upgrade: websocket\r\n">>,<<"Connection: Upgrade\r\n">>,[<<"Sec-Websocket-Protocol:">>,<<"xmpp">>,<<"\r\n">>],<<"Sec-WebSocket-Accept: ">>,<<"xwmiVJXApVi+Tb4YB8gKuT24B7Q=">>,<<"\r\n\r\n">>]
2019-09-17 12:15:06.468 [debug] <0.785.0>@ejabberd_http_ws:init:144 Client connected through websocket {http_ws,<0.785.0>,{{0,0,0,0,0,65535,32512,1},41142}}
2019-09-17 12:15:08.921 [debug] <0.787.0>@ejabberd_http:init:149 S: [{[<<"api">>],mod_http_api},{[<<"bosh">>],mod_bosh},{[<<"upload">>],mod_http_upload},{[<<"ws">>],ejabberd_http_ws},{[<<"captcha">>],ejabberd_captcha},{[<<"admin">>],ejabberd_web_admin}]
2019-09-17 12:15:09.111 [info] <0.535.0>@ejabberd_listener:accept:221 (<0.787.0>) Accepted connection ::ffff:127.0.0.1:41144 -> ::ffff:127.0.0.1:5443
2019-09-17 12:15:09.150 [debug] <0.787.0>@ejabberd_http:process_header:304 ({tlssock,#Port<0.61>,#Ref<0.182672663.2372272129.222007>}) http query: 'GET' <<"/ws/">>
2019-09-17 12:15:09.151 [debug] <0.787.0>@ejabberd_http:process:391 [<<"ws">>] matches [<<"ws">>]
2019-09-17 12:15:09.152 [debug] <0.787.0>@ejabberd_websocket:connect:124 Sent handshake response : [<<"HTTP/1.1 101 Switching Protocols\r\n">>,<<"Upgrade: websocket\r\n">>,<<"Connection: Upgrade\r\n">>,[<<"Sec-Websocket-Protocol:">>,<<"xmpp">>,<<"\r\n">>],<<"Sec-WebSocket-Accept: ">>,<<"ConMIquJt+XuDoNEZWH8fjzn1VU=">>,<<"\r\n\r\n">>]
```

It looks like conversejs enters a connection loop when the first websocket connection drops, failing to notice the server has accepted its re-connection.
I still have no idea why the tcp connection drops in the first place (does conversejs send keepalive packets on the websocket?) nor why conversejs fails to reconnect afterward (or at least fails to detect it has reconnected)?

Here are conversejs options I'm using (in JSON format):
```
    "converse": {
	"allow_contact_requests": false,
	"allow_logout": false,
	"allow_muc_invitations": false,
	"authentication": "anonymous",
	"auto_login": true,
	"auto_join_rooms": [ "forum@conference.gnyoi.com" ],
	"hide_muc_server": true,
	"jid": "gnyoi.com",
	"keepalive": false,
	"message_archiving": "never",
	"muc_disable_moderator_commands": true,
	"notify_all_room_messages": [ "forum@conference.gnyoi.com"	],
	"play_sounds": true,
	"sounds_path": "/conversejs/sounds/",
	"strict_plugin_dependencies": false,
	"trusted": "off",
	"singleton": true,
	"view_mode": "embedded",
	"websocket_url": "wss://testbed-1.gnyoi.com/ws/"
    }
```

ejabberd's configuration is pretty close to the default one, it has both bosh and ws support activated, xep-0198 is also activated (not sure it is relevant here), mod_http_upload is also configured to let conversejs user upload files. I haven't changed ejabberd configuration while upgrading to conversejs-5.0.1 and it used to work with conversejs-4.2.0.

**Comment by jcbrand** [comment]
If you send me login credentials for a test account on your server I'll see what I can do (I can't promise to look into this speedily though, can take some weeks until I have time).

**Comment by joudinet** [comment]
I forgot to precise the nginx configuration for forwarding websocket requests to ejabberd:
```
# Forward Websocket requests to the XMPP server's HTTP listener.
location ^~ /ws {
        proxy_pass       https://127.0.0.1:5443/ws;
        proxy_http_version 1.1;
        proxy_set_header Host           $host;
        proxy_set_header X-Real-IP      $remote_addr;
        proxy_set_header Upgrade        $http_upgrade;
        proxy_set_header Connection     "upgrade";
}
```

I found a solution to avoid the websocket timeout by setting this option in ejabberd configuration:
websocket_ping_interval: 50

The default value is 60s, and it looks like it is too long in my case. I haven't found out how to solve the reconnection errors but at least they don't occur as often as before.

**Comment by jcbrand** [comment]
The reconnection errors sounds like they might be due to a Converse bug.

**Comment by joudinet** [comment]
> If you send me login credentials for a test account on your server I'll see what I can do (I can't promise to look into this speedily though, might take some weeks until I have time).

Unfortunately, the server is not available outside of my LAN. I'll let you know if I find a way to let you have access to a similar settings. Thanks for the proposition.

**Comment by JuliaBonita** [comment]
@jcbrand , are you available for paid consulting work? One of my colleagues who is working with me on this project tried to contact you via your email listed on your GitHub profile, but there was no response. So, maybe it went into your spam box? The project details are confidential right now so I can't post via GitHub yet, but please let me know the best way to contact you privately so you and my colleague (he is more technical than me) can discuss the details.

**Comment by jcbrand** [comment]
@JuliaBonita I'm not currently available because I'm working full time on a Converse-based project. I don't recall getting an email offering consulting work that I didn't respond to. I usually make a point of responding to such emails. I don't see anything in my spam folder. In any case, you're welcome to write to me again, or use my contact form at https://opkode.com/contact.html , I can then refer you to someone who might be able to help.

**Comment by JuliaBonita** [comment]
Ok, thank you @jcbrand . He said he tried sending you a message via your Opkode contact form last week already, but he didn't receive a reply. It's a very interesting project, but he is better at explaining it than me. So, I asked him to send you another message today. Please check your messages and reply to him directly. Thank you.

**Comment by jcbrand** [comment]
@JuliaBonita: I got now another email and noticed that this is someone I did reply to, so most likely my email landed in his spam folder, can you please ask him to check? Thanks

**Comment by jcbrand** [comment]
Closed due to inactivity
