### ISSUE TITLE
Missing/disappearing messages when using indexedDB

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1846]
**Describe the bug**
I can run https://github.com/conversejs/converse-integration-tests on the current master without any issues.

<details>
[17:05:31] XMPP connected
[17:05:38] Logged into Converse
[17:05:38] Testing 1 messages
[17:05:43] Testing 10 online messages with disconnect delay 2..
[17:05:50] Testing 10 offline messages with disconnect delay 2..
[17:05:58] Testing 10 online messages with reload inbetween
[17:05:03] Testing 11 online messages with disconnect delay 5..
[17:05:15] Testing 11 offline messages with disconnect delay 1..
[17:05:21] Testing 11 online messages with reload inbetween
[17:05:26] Testing 12 online messages with disconnect delay 3..
[17:05:36] Testing 12 offline messages with disconnect delay 2..
[17:05:45] Testing 12 online messages with reload inbetween
[17:05:51] Testing 13 online messages with disconnect delay 5..
[17:05:02] Testing 13 offline messages with disconnect delay 3..
[17:05:11] Testing 13 online messages with reload inbetween
[17:05:16] Testing 14 online messages with disconnect delay 5..
[17:05:30] Testing 14 offline messages with disconnect delay 1..
[17:05:38] Testing 14 online messages with reload inbetween
[17:05:43] Testing 15 online messages with disconnect delay 4..
[17:05:54] Testing 15 offline messages with disconnect delay 2..
[17:05:04] Testing 15 online messages with reload inbetween
[17:05:10] Testing 16 online messages with disconnect delay 5..
[17:05:24] Testing 16 offline messages with disconnect delay 2..
[17:05:34] Testing 16 online messages with reload inbetween
[17:05:41] Testing 17 online messages with disconnect delay 0..
[17:05:49] Testing 17 offline messages with disconnect delay 2..
[17:05:00] Testing 17 online messages with reload inbetween
[17:05:07] Testing 18 online messages with disconnect delay 5..
[17:05:22] Testing 18 offline messages with disconnect delay 2..
[17:05:32] Testing 18 online messages with reload inbetween
[17:05:40] Testing 19 online messages with disconnect delay 2..
[17:05:51] Testing 19 offline messages with disconnect delay 3..
[17:05:02] Testing 19 online messages with reload inbetween
</details>

However, adding `persistent_store: 'IndexedDB'` makes the reload test (https://github.com/conversejs/converse-integration-tests/blob/master/test.py#L105) fail reproducibly.

```
[17:05:27] XMPP connected
[17:05:34] Logged into Converse
[17:05:34] Testing 1 messages
[17:05:38] Testing 10 online messages with disconnect delay 4..
[17:05:47] Testing 10 offline messages with disconnect delay 5..
[17:05:56] Testing 10 online messages with reload inbetween
Traceback (most recent call last):
  File "./test.py", line 330, in <module>
    test.test_reload(start_count + i)
  File "./test.py", line 130, in test_reload
    self.checkMessages(private_messages, muc_messages)
  File "./test.py", line 180, in checkMessages
    self.checkPrivateMessages(private_messages)
  File "./test.py", line 214, in checkPrivateMessages
    self.checkPrivateMessage(message, wait)
  File "./test.py", line 284, in checkPrivateMessage
    raise Exception("Private message %s was not received" %(message))
Exception: Private message 06992ddf76dc4ce4b9c2cddfdf32eb84 was not received
```

I manually confirmed the issue; logging in to a Converse instance with IndexedDB and reloading the page while messages are being received, will cause various messages to be lost.

**Comment by jcbrand** [comment]
@laszlovl Could you please check whether this still happens with the latest code on master? I think this might be fixed now.

**Comment by laszlovl** [comment]
I ran the test against a fresh build of the latest master. Unfortunately it immediately reports a failure, even without IndexedDB. So one would have to look into whether there's an actual bug or that Converse's behavior changed significantly enough to break the test architecture.

I don't have plans to work on this anymore, but if anyone else needs help/pointers on it, feel free to ping me.

**Comment by jcbrand** [comment]
Ok, thanks for checking
