### ISSUE TITLE
Duplicate messages after f78837cbc5f468e02a49942211edbc71f6e9f36f

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1856]
https://github.com/conversejs/converse-integration-tests/blob/master/test.py#L132 instantly reports failures since f78837cbc5f468e02a49942211edbc71f6e9f36f

```
[10:10:52] XMPP connected
[10:10:57] Logged into Converse
[10:10:57] Testing 1 messages
[10:10:02] Testing 10 online messages with disconnect delay 1..
Traceback (most recent call last):
  File "./test.py", line 368, in <module>
    test.test_online(start_count + i)
  File "./test.py", line 190, in test_online
    self.checkMessages(private_messages, muc_messages)
  File "./test.py", line 220, in checkMessages
    raise Exception("%s duplicate private messages received" %(self.check_duplicates(private_messages)))
Exception: 10 duplicate private messages received
```

![end](https://user-images.githubusercontent.com/12112486/73730993-ff497900-4737-11ea-9633-97053c2f4d59.png)

**Comment by jcbrand** [comment]
The duplication code will now only look for duplicate message based on the `stanza-id` if the message currently being received is a MAM message with an archive id.

I suspect the reason why your test now fails is because you're testing for duplicate `stanza-id` values but you're not sending full MAM messages but simply normal messages. Is that so?

The change I'm talking about is an optimization to avoid needlessly checking for duplicates and as far as I'm aware we won't ever receive messages with duplicate stanza-ids that are *not* MAM messages.

If it turns out that we do, it's a relatively easy thing to fix though.

**Comment by laszlovl** [comment]
> I suspect the reason why your test now fails is because you're testing for duplicate stanza-id values but you're not sending full MAM messages but simply normal messages. Is that so?

I have no clue (yet) what's even going on under the hood, converse-integration-tests just uses a reasonably modern XMPP client (SleekXMPP) and a modern server configuration (Ejabberd) with all their defaults.

**Comment by jcbrand** [comment]
Thanks, I'll try to fix asap.

**Comment by jcbrand** [comment]
@laszlovl Can you please check whether the problem is now solved?

**Comment by laszlovl** [comment]
Yes, seems fixed, great!

<pre>
[14:02:36] XMPP connected
[14:02:42] Logged into Converse
[14:02:42] Testing 1 messages
[14:02:47] Testing 10 online messages with disconnect delay 2..
[14:02:54] Testing 10 offline messages with disconnect delay 5..
[14:02:03] Testing 10 online messages with reload inbetween
[14:02:07] Testing 11 online messages with disconnect delay 0..
[14:02:12] Testing 11 offline messages with disconnect delay 4..
[14:02:22] Testing 11 online messages with reload inbetween
[14:02:25] Testing 12 online messages with disconnect delay 0..
[14:02:31] Testing 12 offline messages with disconnect delay 3..
[14:02:39] Testing 12 online messages with reload inbetween
[14:02:43] Testing 13 online messages with disconnect delay 1..
[14:02:51] Testing 13 offline messages with disconnect delay 5..
[14:02:01] Testing 13 online messages with reload inbetween
[14:02:06] Testing 14 online messages with disconnect delay 5..
[14:02:16] Testing 14 offline messages with disconnect delay 1..
[14:02:22] Testing 14 online messages with reload inbetween
[14:02:27] Testing 15 online messages with disconnect delay 4..
[14:02:38] Testing 15 offline messages with disconnect delay 4..
[14:02:48] Testing 15 online messages with reload inbetween
[14:02:54] Testing 16 online messages with disconnect delay 0..
[14:02:01] Testing 16 offline messages with disconnect delay 1..
[14:02:08] Testing 16 online messages with reload inbetween
[14:02:14] Testing 17 online messages with disconnect delay 4..
[14:02:25] Testing 17 offline messages with disconnect delay 5..
[14:02:37] Testing 17 online messages with reload inbetween
[14:02:43] Testing 18 online messages with disconnect delay 2..
[14:02:53] Testing 18 offline messages with disconnect delay 3..
[14:02:03] Testing 18 online messages with reload inbetween
[14:02:10] Testing 19 online messages with disconnect delay 4..
[14:02:21] Testing 19 offline messages with disconnect delay 1..
[14:02:29] Testing 19 online messages with reload inbetween
</pre>
