### ISSUE TITLE
Zhabogram component trips Converse

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2181]
HEAD (696c8e35220a99270e05fa470db38a7a7668b55a), Firefox 79
zhabogram is a Telegram gateway [HEAD](https://dev.narayana.im/stuff/zhabogram) _(the site is down now I guess, here's [a mirror](https://github.com/poVoq/zhabogram))_ installed as a component for ejabberd.

```
09:30:16.983  ERROR: Timeout for disco#info query for tlgrm.mydomain.tld log.js:64:19
    log log.js:64
    error log.js:81
    queryInfo converse-disco.js:148
    fetchFeatures converse-disco.js:129
    initialize converse-disco.js:61
    Pi model.js:53
    r helpers.js:25
    _prepareModel collection.js:588
    set collection.js:174
    success collection.js:495
    n storage.js:127
    sync collection.js:92
    fetch collection.js:501
    initialize converse-disco.js:66
    Pi model.js:53
    r helpers.js:25
    _prepareModel collection.js:588
    set collection.js:174
    success collection.js:495
    n storage.js:127
    sync collection.js:92
    fetch collection.js:501
    fetchEntities converse-disco.js:233
    fetchEntities converse-disco.js:232
    i converse-disco.js:353
    Rn events.js:280
    In events.js:264
    e events.js:50
    trigger events.js:254
    trigger converse-core.js:436
    onConnected connection.js:160
    onConnectStatusChanged connection.js:275
    _changeConnectStatus core.js:2383
    _onSessionResultIQ core.js:3003
    run core.js:1259
    _dataRecv core.js:2515
    forEachChild core.js:309
```
...then this longer bit: https://gist.github.com/licaon-kter/bcc1e9aa6b7e249292b2d67b31f17fc2

**Comment by jcbrand** [comment]
Does this actually break Converse, or did you just notice this error in the console?

Looks like zhabogram doesn't respond to disco queries. Ideally Converse should just log the fact that the query timed out and continue as usual.

**Comment by licaon-kter** [comment]
I see a lot of websocket disconnects and reconnects.

I'll have to retest with and without it to confirm this is making things worse.

**Comment by snoopcatt** [comment]
Hello. 
Zhabogram developer is here.

Our git master is not down, it is accessible.

I will take a look what can I do in our side.

**Comment by snoopcatt** [comment]
Please try update zhabogram to [https://git.narayana.im/stuff/zhabogram/src/tag/v2.7](zhabogram v2.7)

**Comment by licaon-kter** [comment]
@snoopcatt Will retry

But since we got you here, the whole thing doesn't really work, Converse errors aside, all commands fail with:
```
D, [27:04.933745 #5070] DEBUG -- XMPPComponent: <presence from='tlgrm.mydomain.tld' to='telegram@domain.tld' type='probe' xmlns='jabber:client'/>
W, [27:26.751772 #5070]  WARN -- XMPPComponent: Message from telegram@domain.tld/yaxim.4BDEF979 to tlgrm.mydomain.tld
D, [27:26.752895 #5070] DEBUG -- XMPPComponent: <message from='telegram@domain.tld/yaxim.4BDEF979' id='V6Eaq-661' xml:lang='en_US' to='tlgrm.mydomain.tld' type='chat' xmlns='jabber:client'><request xmlns='urn:xmpp:receipts'/><body>/login NUMBER</body></message>
/home/user/zhabogram/inc/telegramclient.rb:291: warning: instance variable @telegram not initialized
E, [27:28.870551 #5070] ERROR -- XMPPComponent: undefined method `set_authentication_phone_number' for nil:NilClass (NoMethodError)
/home/user/zhabogram/inc/telegramclient.rb:291:in `process_command'
/home/user/zhabogram/inc/telegramclient.rb:278:in `process_outgoing_message'
/home/user/zhabogram/inc/xmppcomponent.rb:66:in `handle_message'
/home/user/zhabogram/inc/xmppcomponent.rb:24:in `block in connect'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/callbacks.rb:99:in `block in process'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/callbacks.rb:98:in `each'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/callbacks.rb:98:in `process'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:277:in `receive'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:74:in `block in parse'
/usr/lib/ruby/2.5.0/rexml/parsers/sax2parser.rb:143:in `block in parse'
/usr/lib/ruby/2.5.0/rexml/parsers/sax2parser.rb:143:in `each'
/usr/lib/ruby/2.5.0/rexml/parsers/sax2parser.rb:143:in `parse'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91:in `parse'
/usr/share/rubygems-integration/all/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
W, [27:28.884620 #5070]  WARN -- XMPPComponent: Connected to XMPP server
I, [27:28.886801 #5070]  INFO -- XMPPComponent: Got presence :probe from tlgrm.mydomain.tld to telegram@domain.tld
D, [27:28.887761 #5070] DEBUG -- XMPPComponent: <presence from='tlgrm.mydomain.tld' to='telegram@domain.tld' type='probe' xmlns='jabber:client'/>
```
What am I missing? Debian Buster, arm64

**Comment by snoopcatt** [comment]
Have you test latest version from git?

**Comment by licaon-kter** [comment]
@snoopcatt of course, that's HEAD

**Comment by snoopcatt** [comment]
You can add me pd at narayana dot im and we will try to investigate this.

**Comment by licaon-kter** [comment]
@snoopcatt `Authentication failed: Peer responded with error: unable to get local issuer certificate (not-authorized)` when trying to write to you

**Comment by snoopcatt** [comment]
You server should have valid SSL certificate.

**Comment by licaon-kter** [comment]
@snoopcatt imagine that I do, you reject Let's Encrypt?

**Comment by snoopcatt** [comment]
I hope we have fixed this issue.

**Comment by licaon-kter** [comment]
Appears fixed, thanks @snoopcatt
