### ISSUE TITLE
converse..js 6.0.1 authentication prebind error

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#2313]
Hi everyone,

converse.js 6.0.1
ejabberd-20.03 as xmpp server
Ubuntu 18.04 as OS

I got some troubles with authentication prebind when trying to integration converse.js on my website.

Here is my configuration setting.

```
converse.initialize({

	enable_smacks: true,
	bosh_service_url: bosh_service_url,
	authentication: 'prebind',
        prebind_url: prebind_url,

	auto_login: true,
	keepalive: true,
	auto_reconnect: true,

       	message_carbons: true,
       	play_sounds: true,
	sounds_path: sounds_path,
       	roster_groups: true,
       	show_controlbox_by_default: false,
	allow_logout: false,
	use_vcards: true,
	view_mode: view_mode,
	allow_message_corrections: "all",
	allow_message_retraction: "all",
	omemo_default: true,
        allow_muc: true,
	auto_list_rooms: false,
        notification_icon: notification_icon + 'logo.png',
        muc_instant_rooms: true,
        allow_muc_invitations: true,
        allow_non_roster_messaging: true,
        allow_chat_pending_contacts: true,
        allow_contact_requests: false,
	show_chat_state_notifications: true,
        message_archiving: 'always',
        i18n: language_code,
        csi_waiting_time: 420,
        auto_away: 120,
	//auto_xa: 120,
	idle_presence_timeout: 300,
        ping_interval: 60,
        archived_messages_page_size: 50,
	show_desktop_notifications: 'all',
	send_chat_state_notifications: true,
	show_images_inline: true,
	allow_dragresize: true,
	auto_focus: true,
	autocomplete_add_contact: true,
	hide_offline_users: false,
        default_domain : userxmppdomain,
        allow_contact_removal: false,
        allow_registration: false,
        strict_plugin_dependencies: false,
        synchronize_availability: true,
	muc_domain: "conference."+userxmppdomain,
	locked_muc_domain: "hidden",
	muc_mention_autocomplete_min_chars: 3,
	muc_mention_autocomplete_filter: 'contains',
	muc_mention_autocomplete_show_avatar: true,
	notify_all_room_messages: true,
	muc_respect_autojoin: false,
	muc_show_logs_before_join: true,
	muc_instant_rooms: false,
	muc_show_join_leave: true,
	muc_show_join_leave_status: true,
	show_client_info: false,
	theme: "default",//concord  
	loglevel: 'fatal',
	//loglevel: 'debug','debug', 'info', 'warn', 'error', 'fatal'
	persistent_store: 'IndexedDB',

        visible_toolbar_buttons: {
    		spoiler: true,
   		emoji: true,
    		toggle_occupants: true
        },

    });
```
Here is the json I got from prebind_url;

`{"rid":1370132405,"sid":"c71d81d213ebcf13bc7fcc5b6f135a01d2212129","jid":"pessek@pessek-mysite.com"}`

Here is the fatal error I got in my browser console.

**Opera browser's console:**

`FATAL: TypeError: Cannot read property 'focus' of null    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:96796)    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:104286)    at i.wrappedOverride (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:231944)    at e.exports (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:67:16824)    at i.t (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:145054)    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:178:89668)    at i.wrappedOverride (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:231944)    at e.exports (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:67:16824)    at i.t [as renderLoginPanel] (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:145054)    at i.render (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:95986)`

**Chrome browser's console.**

```
FATAL: TypeError: Cannot read property 'focus' of null    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:96796)    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:104286)    at i.wrappedOverride (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:231944)    at e.exports (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:67:16824)    at i.t (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:145054)    at i.renderLoginPanel (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:178:89668)    at i.wrappedOverride (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:231944)    at e.exports (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:67:16824)    at i.t [as renderLoginPanel] (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:121:145054)    at i.render (https://pessek-mysite.com/mod/pessek_chat/dist/converse.min.js:158:95986)
Uncaught (in promise) TypeError: Cannot read property 'model' of undefined
    at Object.r (converse-controlbox.js:606)
    at m (backbone.js:334)
    at p (backbone.js:322)
    at l (backbone.js:110)
    at Object.a.trigger (backbone.js:312)
    at Object.trigger (converse-core.js:1350)
    at Et (converse-core.js:553)
    at Object.reconnect (converse-core.js:1308)
    at Object.onDisconnected (converse-core.js:1105)
    at j.Connection.onConnectStatusChanged [as connect_callback] (converse-core.js:1151)
```

Could someone help me with this issue ?

Regards,

**Comment by jcbrand** [comment]
Sorry, no longer looking into issues on Converse 6
