### ISSUE TITLE
Question about test

### ISSUE THREAD

**Issue by HumanG33k** [conversejs/converse.js#2515]
I try to excute test and i have several  

```
 Disconnected (0 times), because no message in 3 Chrome 90.0.4430.212 (Linux x86_64) ERROR

ERROR: '%c ERROR: Rejecting carbon from invalid JID romeo@montague.lit/orchard', 'color: maroon'

```

There is something to configure or just make as write in readme : 
```
make check
```

**Comment by jcbrand** [comment]
Running `make check` is enough. You haven't provided enough information to know what's going on.

**Comment by HumanG33k** [comment]
no running : make check is not enought. 
chromium is needed and also setup a var env.
Strangely the test also start psy the xmpp client. It's not my main xmpp client but it's probably a wrong conf on my side (xdg open).

This is a more complete extract of my log. 
```
Chrome 90.0.4430.212 (Linux x86_64): Executed 284 of 434 (5 FAILED) (skipped 1) (0 secs / 1 min 30.7 secs)
Chrome 90.0.4430.212 (Linux x86_64) Message Retractions A Sent Groupchat Message can be retracted by its author, causing an error message in response FAILED
Chrome 90.0.4430.212 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: [object Element] thrown
  Unhandled promise rejection: Error: Timeout Error: No response from server
  Error: Timeout Error: No response from server
      at TimedHandler.handler (dist/converse.js:69846:26)
      at TimedHandler.run (dist/converse.js:2288:17)
      at connection_MockConnection._onIdle (dist/converse.js:4261:21)
      at dist/converse.js:35100:59
  Unhandled promise rejection: Error: Timeout Error: No response from server
  Error: Timeout Error: No response from server
      at TimedHandler.handler (dist/converse.js:69846:26)
      at TimedHandler.run (dist/converse.js:2288:17)
      at connection_MockConnection._onIdle (dist/converse.js:4261:21)
      at dist/converse.js:35100:59
Chrome 90.0.4430.212 (Linux x86_64): Executed 287 of 434 (5 FAILED) (skipped 1) ERROR (0 secs / 1 min 32.005 secs)
Chrome 90.0.4430.212 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: [object Element] thrown
  Unhandled promise rejection: Error: Timeout Error: No response from server
  Error: Timeout Error: No response from server
      at TimedHandler.handler (dist/converse.js:69846:26)
      at TimedHandler.run (dist/converse.js:2288:17)
      at connection_MockConnection._onIdle (dist/converse.js:4261:21)
      at dist/converse.js:35100:59
  Unhandled promise rejection: Error: Timeout Error: No response from server
  Error: Timeout Error: No response from server
      at TimedHandler.handler (dist/converse.js:69846:26)
      at TimedHandler.run (dist/converse.js:2288:17)
      at connection_MockConnection._onIdle (dist/converse.js:4261:21)
Chrome 90.0.4430.212 (Linux x86_64): Executed 287 of 434 (5 FAILED) (skipped 1) ERROR (1 min 35.275 secs / 1 min 32.005 secs)

```
It's look strange there is a release not passing testes. We try to beta test conversejs in chatons (kittens) initiative but we want to be sure is "production ready".
We already have several feedback of our testers. We want to go a little far away and run tests before upgrade.

**Comment by jcbrand** [comment]
What is the issue here? I don't understand what the point you're trying to make is.

**Comment by HumanG33k** [comment]
It's more having questions.
I want to understand why there is time out.  Time out not look as part of the execution test plan are they  ? 
Why test take so long to be execute. 
If it's the normal behavior some tests failed in a release version ?

**Comment by jcbrand** [comment]
No it's not normal behaviour and you can see that tests are usually green:
https://travis-ci.org/github/conversejs/converse.js/builds
