### ISSUE TITLE
Failing to build source in branch 7.x.x

### ISSUE THREAD

**Issue by lunika** [conversejs/converse.js#2729]
**Describe the bug**

We want to build converse.js from the source following this documentation https://github.com/conversejs/converse.js/blob/7.x.x/docs/source/dependencies.rst

node 12 is used with nvm:

```
$ nvm use
Found '/home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/.nvmrc' with version <v12.13.1>
Now using node v12.13.1 (npm v6.12.1)
```

I have checkout on branch `7.x.x`

```
$ git checkout 7.x.x
Switched to branch '7.x.x'
Your branch is up to date with 'origin/7.x.x'.
```

and then I run `make dev`

```
$ make dev
npm install lerna
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.

> sleep@3.0.1 install /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/sleep
> node-gyp rebuild

make[1]: Entering directory '/home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:6:11: error: ‘Handle’ has not been declared in ‘v8’
    6 | using v8::Handle;
      |           ^~~~~~
../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:42:30: error: no matching function for call to ‘v8::Value::Uint32Value()’
   42 |   sleep(info[0]->Uint32Value());
      |                              ^
In file included from /home/manu/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
 2611 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: note:   candidate expects 1 argument, 0 provided
../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE USleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:54:31: error: no matching function for call to ‘v8::Value::Uint32Value()’
   54 |   usleep(info[0]->Uint32Value());
      |                               ^
In file included from /home/manu/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
 2611 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: note:   candidate expects 1 argument, 0 provided
../sleep.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../sleep.cc:62:52: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   62 |     Nan::New<FunctionTemplate>(Sleep)->GetFunction());
      |                                                    ^
In file included from /home/manu/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 5995 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
../sleep.cc:64:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   64 |     Nan::New<FunctionTemplate>(USleep)->GetFunction());
      |                                                     ^
In file included from /home/manu/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 5995 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
In file included from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
../sleep.cc: At global scope:
/home/manu/.cache/node-gyp/12.13.1/include/node/node.h:566:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  566 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/node.h:600:3: note: in expansion of macro ‘NODE_MODULE_X’
  600 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../sleep.cc:68:1: note: in expansion of macro ‘NODE_MODULE’
   68 | NODE_MODULE(node_sleep, init)
      | ^~~~~~~~~~~
In file included from /home/manu/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../sleep.cc:2:
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/manu/.cache/node-gyp/12.13.1/include/node/node_object_wrap.h:84:78:   required from here
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10004 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/manu/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make[1]: *** [node_sleep.target.mk:109: Release/obj.target/node_sleep/sleep.o] Error 1
make[1]: Leaving directory '/home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/manu/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.11.0-40-generic
gyp ERR! command "/home/manu/.nvm/versions/node/v12.13.1/bin/node" "/home/manu/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/sleep
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> node-sass@4.14.1 install /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/manu/.npm/node-sass/4.14.1/linux-x64-72_binding.node

> node-sass@4.14.1 postinstall /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass
> node scripts/build.js

Binary found at /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 (node_modules/sleep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ lerna@3.22.1
added 2242 packages from 2336 contributors and audited 2248 packages in 40.328s
found 139 vulnerabilities (71 moderate, 67 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
npm run lerna

> converse.js@7.0.6 lerna /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js
> lerna bootstrap --hoist --ignore-scripts

lerna notice cli v3.22.1
lerna info Bootstrapping 2 packages
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 2 packages
npm rebuild node-sass

> node-sass@4.14.1 install /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass/vendor/linux-x64-72/binding.node

> node-sass@4.14.1 postinstall /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass
> node scripts/build.js

Binary found at /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
node-sass@4.14.1 /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/node-sass
npm run dev

> converse.js@7.0.6 dev /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js
> webpack --config webpack.dev.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
Building unminified package for Native JavaScript for Bootstrap 4 v2.0.27 ..
Included modules: Alert, Button, Collapse, Dropdown, Modal, Popover, Tab, Toast, Tooltip
Build complete!

Hash: 74ee0dc14d86d1b48e02
Version: webpack 4.46.0
Time: 14294ms
Built at: 11/19/2021 11:06:31 AM
 390 assets
Entrypoint main = ../dist/converse.min.css ../dist/converse.css converse.js ../dist/converse.min.css.map ../dist/converse.css.map converse.js.map
 [60] ./src/templates/form_input.html 356 bytes {158} [built] [failed] [1 error]
 [61] ./src/templates/form_username.html 300 bytes {158} [built] [failed] [1 error]
 [62] ./src/lodash.noconflict.js 62 bytes {158} [built]
[170] ./src/templates/controlbox_toggle.html 294 bytes {158} [built] [failed] [1 error]
[171] ./src/templates/dragresize.html 385 bytes {158} [built] [failed] [1 error]
[174] ./src/templates/register_panel.html 388 bytes {158} [built] [failed] [1 error]
[175] ./src/templates/registration_form.html 429 bytes {158} [built] [failed] [1 error]
[176] ./src/templates/registration_request.html 407 bytes {158} [built] [failed] [1 error]
[177] ./src/templates/group_header.html 503 bytes {158} [built] [failed] [1 error]
[178] ./src/templates/pending_contact.html 344 bytes {158} [built] [failed] [1 error]
[179] ./src/templates/requesting_contact.html 328 bytes {158} [built] [failed] [1 error]
[180] ./src/templates/roster.html 492 bytes {158} [built] [failed] [1 error]
[319] ./src/entry.js 2.19 KiB {158} [built]
[493] ./sass/converse.scss 1.96 KiB {158} [built]
[498] ./src/converse.js + 495 modules 1.56 MiB {158} [built]
      | ./src/converse.js 2.75 KiB [built]
      | ./src/headless/converse-core.js 59.1 KiB [built]
      | ./src/headless/headless.js 1.12 KiB [built]
      | ./src/i18n/index.js 3.94 KiB [built]
      | ./src/converse-registry.js 374 bytes [built]
      | ./src/converse-autocomplete.js 12 KiB [built]
      | ./src/converse-bookmark-views.js 9.89 KiB [built]
      | ./src/converse-chatview.js 42 KiB [built]
      | ./src/converse-controlbox.js 19.7 KiB [built]
      | ./src/converse-dragresize.js 13.3 KiB [built]
      | ./src/converse-singleton.js 1.31 KiB [built]
      | ./src/converse-fullscreen.js 664 bytes [built]
      | ./src/converse-mam-views.js 1.28 KiB [built]
      | ./src/converse-minimize.js 15.6 KiB [built]
      | ./src/converse-muc-views.js 61.9 KiB [built]
      |     + 481 hidden modules
    + 857 hidden modules

WARNING in ./node_modules/dayjs/locale/types.d.ts 1:8
Module parse failed: Unexpected token (1:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> declare interface ILocale {
|   name: string
|   weekdays?: string[]
 @ ./node_modules/dayjs/locale lazy ^\.\/.*$ namespace object ./types.d.ts
 @ ./src/i18n/index.js
 @ ./src/converse.js
 @ ./src/entry.js

WARNING in ./node_modules/dayjs/locale/index.d.ts 3:8
Module parse failed: Unexpected token (3:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /// <reference path="./types.d.ts" />
| 
> declare module 'dayjs/locale/*' {
|   namespace locale {
|     interface Locale extends ILocale {}
 @ ./node_modules/dayjs/locale lazy ^\.\/.*$ namespace object ./index.d.ts
 @ ./src/i18n/index.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/room_description.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!-- FIXME: check markup in mockup -->
| <div class="room-info">
| <p class="room-info"><strong>{{{o.label_jid}}}</strong> {{{o.jid}}}</p>
 @ ./src/modals/muc-list.js 4:0-67 28:37-57
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./images/icons.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="UTF-8"?>
| <!--
| Font Awesome Free 5.13.0 by @fontawesome - https://fontawesome.com
 @ ./src/components/font-awesome.js 8:20-10:29
 @ ./src/templates/converse.js
 @ ./src/converse-chatboxviews.js
 @ ./src/converse-chatview.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/roster_item.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <a class="list-item-link cbox-list-item open-chat w-100 {[ if (o.num_unread) { ]} unread-msgs {[ } ]}"
|    title="{{{o.desc_chat}}}" href="#">
| 
 @ ./src/converse-rosterview.js 16:0-57 423:28-43
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/group_header.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <a href="#" class="list-toggle group-toggle controlbox-padded" title="{{{o.desc_group_toggle}}}">
|     <span class="fa {[ if (o.toggle_state === o._converse.OPENED) { ]} fa-caret-down {[ } else { ]} fa-caret-right {[ } ]}">
|     </span> {{{o.label_group}}}</a>
 @ ./src/converse-rosterview.js 11:0-59 565:28-44
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/roster.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="d-flex controlbox-padded">
|     <span class="w-100 controlbox-heading controlbox-heading--contacts">{{{o.heading_contacts}}}</span>
|     <a class="controlbox-heading__btn sync-contacts fa fa-sync" title="{{{o.title_sync_contacts}}}"></a>
 @ ./src/converse-rosterview.js 14:0-47 789:28-38
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/dragresize.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="dragresize dragresize-top"></div>
| <div class="dragresize dragresize-topleft"></div>
| <div class="dragresize dragresize-left"></div>
 @ ./src/converse-dragresize.js 10:0-55 16:18-32
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_checkbox.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="form-group">
|     <input id="{{{o.id}}}" name="{{{o.name}}}" type="checkbox" {{{o.checked}}} {[ if (o.required) { ]} required {[ } ]} />
|     <label class="form-check-label" for="{{{o.id}}}">{{{o.label}}}</label>
 @ ./src/utils/html.js 11:0-64 676:11-28
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_select.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="form-group">
|     <label for="{{{o.id}}}">{{{o.label}}}</label>
|     <select class="form-control" id="{{{o.id}}}" name="{{{o.name}}}" {[ if (o.multiple) { ]} multiple="multiple" {[ } ]}>{{o.options}}</select>
 @ ./src/utils/html.js 13:0-60 650:11-26
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_username.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="form-group">
|     {[ if (o.label) { ]}
|     <label>
 @ ./src/utils/html.js 16:0-64 693:11-28
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_input.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div class="form-group">
|     {[ if (o.type !== 'hidden') { ]}
|         <label for="{{{o.id}}}">{{{o.label}}}</label>
 @ ./src/utils/html.js 12:0-58 716:11-25
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/register_panel.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <div>
|     <form id="converse-register" class="converse-form">
|         <legend class="col-form-label">{{{o.__("Create your account")}}}</legend>
 @ ./src/converse-register.js 13:0-63 151:28-46
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_textarea.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <label class="label-ta">{{{o.label}}}</label>
| <textarea name="{{{o.name}}}">{{{o.value}}}</textarea>
| 
 @ ./src/utils/html.js 14:0-64 666:11-28
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_url.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <label>
|     {{{o.label}}}
|     <a class="form-url" target="_blank" rel="noopener" href="{{{o.value}}}">{{{o.value}}}</a>
 @ ./src/utils/html.js 15:0-54 686:11-23
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/registration_form.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <legend class="col-form-label">{{{o.__("Account Registration:")}}} {{{o.domain}}}</legend>
| <p class="title">{{{o.title}}}</p>
| <p class="form-help instructions">{{{o.instructions}}}</p>
 @ ./src/converse-register.js 14:0-69 464:25-46
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/select_option.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <option value="{{{o.value}}}" {[ if (o.selected) { ]} selected="selected" {[ } ]} >{{{o.label}}}</option>
| 
 @ ./src/utils/html.js 18:0-64 643:13-30
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/registration_request.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <span class="spinner login-submit fa fa-spinner"></span>
| <p class="info">{{{o.__("Hold tight, we're fetching the registration form…")}}}</p>
| {[ if (o.cancel) { ]}
 @ ./src/converse-register.js 15:0-75 351:69-93
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/controlbox_toggle.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <span class="toggle-feedback">{{{o.label_toggle}}}</span>
| 
 @ ./src/converse-controlbox.js 11:0-69 514:28-49
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/pending_contact.html 1:3
Module parse failed: Unexpected token (1:3)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {[ if (o.allow_chat_pending_contacts)  { ]}
| <a class="list-item-link open-chat w-100" href="#">
| {[ } ]}
 @ ./src/converse-rosterview.js 12:0-65 365:30-49
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/requesting_contact.html 1:3
Module parse failed: Unexpected token (1:3)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {[ if (o.allow_chat_pending_contacts)  { ]}
| <a class="open-chat w-100"href="#">
| {[ } ]}
 @ ./src/converse-rosterview.js 13:0-71 373:30-52
 @ ./src/converse.js
 @ ./src/entry.js

ERROR in ./src/templates/form_captcha.html 1:3
Module parse failed: Unexpected token (1:3)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {[ if (o.label) { ]}
| <label>
|     {{{o.label}}}
 @ ./src/utils/html.js 10:0-62 705:11-27
 @ ./src/dom-navigator.js
 @ ./src/components/dropdown.js
 @ ./src/templates/chatroom_head.js
 @ ./src/converse-muc-views.js
 @ ./src/converse.js
 @ ./src/entry.js
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--11-1!node_modules/postcss-loader/src/index.js!node_modules/sass-loader/dist/cjs.js??ref--11-3!sass/converse.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--11-3!./sass/converse.scss 749 KiB {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! converse.js@7.0.6 dev: `webpack --config webpack.dev.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the converse.js@7.0.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/manu/.npm/_logs/2021-11-19T10_06_31_309Z-debug.log
make: *** [Makefile:130: dev] Error 2
```

And here is the content of `/home/manu/.npm/_logs/2021-11-19T10_06_31_309Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/manu/.nvm/versions/node/v12.13.1/bin/node',
1 verbose cli   '/home/manu/.nvm/versions/node/v12.13.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle converse.js@7.0.6~predev: converse.js@7.0.6
6 info lifecycle converse.js@7.0.6~dev: converse.js@7.0.6
7 verbose lifecycle converse.js@7.0.6~dev: unsafe-perm in lifecycle true
8 verbose lifecycle converse.js@7.0.6~dev: PATH: /home/manu/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js/node_modules/.bin:/home/manu/dev/fun/marsha/src/frontend/node_modules/.bin:/home/manu/.nvm/versions/node/v12.13.1/bin:/home/manu/bin:/home/manu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/manu/.yarn/bin:/home/manu/go/bin:/home/manu/.krew/bin:/home/manu/.yarn/bin:/home/manu/go/bin:/home/manu/.krew/bin
9 verbose lifecycle converse.js@7.0.6~dev: CWD: /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js
10 silly lifecycle converse.js@7.0.6~dev: Args: [ '-c', 'webpack --config webpack.dev.js' ]
11 silly lifecycle converse.js@7.0.6~dev: Returned: code: 2  signal: null
12 info lifecycle converse.js@7.0.6~dev: Failed to exec dev script
13 verbose stack Error: converse.js@7.0.6 dev: `webpack --config webpack.dev.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/manu/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/home/manu/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid converse.js@7.0.6
15 verbose cwd /home/manu/dev/fun/marsha/src/frontend/node_modules/converse.js
16 verbose Linux 5.11.0-40-generic
17 verbose argv "/home/manu/.nvm/versions/node/v12.13.1/bin/node" "/home/manu/.nvm/versions/node/v12.13.1/bin/npm" "run" "dev"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 2
22 error converse.js@7.0.6 dev: `webpack --config webpack.dev.js`
22 error Exit status 2
23 error Failed at the converse.js@7.0.6 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Environment (please complete the following information):**

- ubuntu 21.04
- using nvm as described before

Any idea of what is happening ?

**Comment by jcbrand** [comment]
I don't know, perhaps you're using a NodeJS version that's not supported. :shrug:

**Comment by lunika** [comment]
I'm using the node version you added in the file `.nvmrc`. It's disturbing if you don't know if the version you added in your project is supported or not.

**Comment by jcbrand** [comment]
Ok, so maybe it's right. I don't know. I don't work on that version anymore and I never promised to support older versions, especially not for free.
