### ISSUE TITLE
Auto join MUC after autologin issue

### ISSUE THREAD

**Issue by fenix011** [conversejs/converse.js#3056]
**Describe the bug**

**To Reproduce**

Initialized converse with (amongst others)  authentication: 'login',      auto_login: true,      auto_join_rooms:  [ the givenMUC here  ... ] a user 's  JID and password .

**Expected behavior**
I expect to auto-join the 'givenMUC'. No joy for now, though.

**Environment (please complete the following information):**
 - Desktop 
 - Browser : same issue in Chrome and Firefox
 - Converse.js version :  9.1

**Additional context**

Functional Prosody 0.12 server in use. 

 Thanks, thanks, thanks !

**Comment by fenix011** [comment]
Ah... if inspect the console log in my browser, i'm getting :

```
controlbox.js:10 connection_status
controlbox.js:11 6
log.js:66  2022-10-22T13:12:52.080Z WARNING: Could not restore session for jid: converse@librebits.info/converse.js-95653936 Error message: _restore: no restoreable session. 
log @ log.js:66
librebits.info/.well-known/host-meta:1          Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
log.js:64  ERROR: Failed to discover alternative connection methods at https://librebits.info/.well-known/host-meta
log @ log.js:64
log.js:64  ERROR: TypeError: Failed to fetch    at Oc.discoverConnectionMethods (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:189282)    at Oc.connect (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:189626)    at Fc (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:200508)    at Lc (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:198627)    at Object.login (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:247154)    at async initialize (https://cdn.conversejs.org/9.1.1/dist/converse.min.js:2:252710)
log @ log.js:64
controlbox.js:10 connection_status
controlbox.js:11 1
log.js:72  2022-10-22T13:12:52.853Z INFO: SASL authentication succeeded. 
controlbox.js:10 connection_status
controlbox.js:11 5
log.js:64  ERROR: <iq xmlns="jabber:client" id="18a80cb4-bdbd-4d50-a53c-c4104e5dd121:sendIQ" from="hall@librebits.info" to="converse@librebits.info/converse.js-95653936" type="error"><error type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
log @ log.js:64
```

umh... while i'm using dev.myconverse.net and the Prosody server is in mydomain.net , could it be that this log message : 

```
[..]
librebits.info/.well-known/host-meta:1          Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
[..]
``` 

is showing a CORS problem ? i'm wondering... How to double check ?
