### ISSUE TITLE
Cannot send messages with OMEMO

### ISSUE THREAD

**Issue by diego-treitos** [conversejs/converse.js#3099]
**Describe the bug**
I've configured an account in the conversejs Desktop application. Then I've configured a contact and trusted the fingerprints in both sides.
ConverseJS is able to receive encrypted messages using OMEMO, however it cannot send them.
After opening the debug window I see several errors:

```
ERROR: Could not fetch bundle for device <id> from <conversejs_account>
ERROR: <iq xmlns="jabber:client" type="error" id="71746618-292f-416d-89ab-8727d6ee9b20:sendIQ" to="<conversejs_account>/converse.js-101802182"><error type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
ERROR: Could not build an OMEMO session for device <id> because we don't have its bundle
ERROR: Error: No record for <conversejs_account>.<id>
    at SessionCipher.<anonymous> (file:///tmp/.mount_converNGKhIe/resources/app.asar/3rdparty/libsignal-protocol.js:36052:21)
libsignal-protocol.js:36052 Uncaught (in promise) Error: No record for <conversejs_account>.<id>    at SessionCipher.<anonymous> (libsignal-protocol.js:36052:21)
```

**To Reproduce**
1. Open the ConverseJS desktop app
2. Try to send a message to a trusted contact

**Expected behavior**
Being able to send messages

**Environment (please complete the following information):**
 - Using ConverseJS desktop AppImage: converse_desktop-10.0.0_x86_64.AppImage
 
**Additional context**
Note that if I use a diferent client from converseJS, I am able to talk with the other contact, although this other client does not use BOSH.

**Comment by licaon-kter** [comment]
In contact details do you see their keys?

**Comment by diego-treitos** [comment]
Hi @licaon-kter thank you for replying. I do see their keys and I have trusted them.

Also I can receive their encrypted messages and decrypt them.

**Comment by diego-treitos** [comment]
@licaon-kter I should also mention that I've configured the server and added bosh support to it. I am not sure if there is any special configuration required to support OMEMO with BOSH. I certainly didn't see any reference to this in the prosody (xmpp server) documentation.

**Comment by diego-treitos** [comment]
I am using `prosody 0.12.1`. I didn't try websockets... let me check that up :)

**Comment by diego-treitos** [comment]
@licaon-kter Unfortunately via websockets the error is the same :(

**Comment by licaon-kter** [comment]
Can you try with another contact? Eg. Make a random account on conversations.im

**Comment by diego-treitos** [comment]
@licaon-kter I've just tested several things:

* Created a new contact `test3` (same server) and test it with a different client (dino) keeping the other contact `test2` in conversejs. Same errors.

* Switched accounts: `test3` in conversejs and `test2` in dino. Same errors

* Created accounts in conversations.im. I think the free tier might not support OMEMO? Dino reported that the contact in conversejs did not have OMEMO support... Maybe the free tier does not have PEP enabled? (no fingerprint was shown in any client for any contact)

Do you think there could be anything wrong in the server regarding websockets+OMEMO or bosh+OMEMO?

**Comment by licaon-kter** [comment]
conversations.im is free for a long time, there's no "tier"

Can you login with separate instances of Converse Desktop, into those 2 conversations.im accounts?

**Comment by licaon-kter** [comment]
Did you test with https://github.com/conversejs/converse-tauri too?

**Comment by diego-treitos** [comment]
I am afraid I didn't but I actually needed the Converse-desktop client to work so it can be used by other people. I was actually testing it but so far I had no luck when using OMEMO (unencrypted chat works).

Also other clients work with OMEMO, but they dont use BOSH or websockets...

**Comment by licaon-kter** [comment]
The Tauri client is like Desktop, do try it.

To eliminate any (of your own) server issue, try between Desktop and Tauri with the conversations.im accounts first.

**Comment by diego-treitos** [comment]
@licaon-kter THank you for the follow up.

I've tested with tauri. However when using the conversations.im accounts I get that OMEMO is not supported by the other client in both ends. I think this probably has to do with conversations.im.

Then I used my server and again I have the very same problem in both ends.

Also, if there was a problem in my server, why do other clients work? Even the movim client, via web (BOSH or websockets) worked just fine with OMEMO.

**Comment by licaon-kter** [comment]
>  I think this probably has to do with conversations.im.

You keep saying that, but it's not true.

For now I can conclude it's a Desktop app issue.

Now, can you try _(with both accounts on your server_ using the web version in a browser: **(normal session NOT private)**
 https://conversejs.org/fullscreen.html

_(Don't forget to have "This is a trusted device" checkbox!)_

**Comment by diego-treitos** [comment]
@licaon-kter Do you need me to share with you the server configuration for prosody? I really doubt it is a problem on the server side as every other client works, but just in case. Also if you can provide me with a known working configuration for prosody that would be awesome too.

**Comment by licaon-kter** [comment]
Not really a Prosody person, but do attach a link with the gist of the config (cleaned).

**Comment by diego-treitos** [comment]
Here is the gist for the `prosody.cfg.lua` file: https://gist.github.com/diego-treitos/bb36611891b60de80c3e16fb613955e8

**Comment by jcbrand** [comment]
The `item-not-found` error indicates that the user doesn't have a bundle published. Doesn't seem to be a Converse issue. Closing.
