### ISSUE TITLE
Uncaught ReferenceError: can't access lexical declaration 'iy' before initialization

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#3243]
Local build of https://github.com/conversejs/converse.js/commit/69ba2dd7fa31dbd82dc7b9461015c0803f5a4e97

Firefox Stable debug console says:
```
Uncaught ReferenceError: can't access lexical declaration 'iy' before initialization
    685 index.js:9
    Webpack 4
        o
        load
        initialize
        <anonymous>
```

**Comment by singpolyma** [comment]
I have this issue also, unminified I get `Uncaught ReferenceError: can't access lexical declaration '__WEBPACK_DEFAULT_EXPORT__' before initialization`

**Comment by jcbrand** [comment]
Thanks guys, I'm aware of the issue. Looks like a circular import due to some refactoring I've been doing.

**Comment by licaon-kter** [comment]
8404cb41dfd757776dfef4f9e80edb4d6bb8de05 says
```
feed.js:6 Uncaught ReferenceError: Cannot access 'chat_model' before initialization
    at 4947 (feed.js:6:44)
    at __webpack_require__ (bootstrap:19:1)
    at Object.load (entry.js:60:9)
    at Object.initialize (entry.js:31:25)
    at (index):1:689
```

**Comment by jcbrand** [comment]
I think this might be fixed now, but I haven't had time to check in detail.

**Comment by jcbrand** [comment]
Thanks @SilverYoCha, I forgot to commit a new file

**Comment by licaon-kter** [comment]
Still seeing 
```
[Error] ReferenceError: Cannot access uninitialized variable.
	3824 (converse.js:35619)
	__webpack_require__ (converse.js:83336)
	load (converse.js:83689)
	initialize (converse.js:83659)
	Global Code (chat:1:700)
```
with 70490b39757a2bd30d80a8b5deff254255434f60

**Comment by paulmenzel** [comment]
Bisection points to commit 521d3ae9eafb4c98fedeb716e0c17ade0d001f39:

```
> git bisect good
521d3ae9eafb4c98fedeb716e0c17ade0d001f39 is the first bad commit
commit 521d3ae9eafb4c98fedeb716e0c17ade0d001f39
Author: JC Brand <jc@opkode.com>
Date:   Mon Jul 17 09:02:19 2023 +0200

    Set `main` attribute in `package.json`
    
    Don't set `strophe.js` as dependency twice.

 package-lock.json         | 1 -
 package.json              | 2 +-
 src/headless/package.json | 3 ++-
 3 files changed, 3 insertions(+), 3 deletions(-)
```

```
> git bisect log
git bisect start
# status: waiting for both good and bad commits
# good: [d5deed087195e9835452503d31fe51e5fef53b10] Release 10.0.0
git bisect good d5deed087195e9835452503d31fe51e5fef53b10
# status: waiting for bad commit, 1 good commit known
# bad: [70490b39757a2bd30d80a8b5deff254255434f60] Update readme after 10.1.6 release
git bisect bad 70490b39757a2bd30d80a8b5deff254255434f60
# bad: [70490b39757a2bd30d80a8b5deff254255434f60] Update readme after 10.1.6 release
git bisect bad 70490b39757a2bd30d80a8b5deff254255434f60
# skip: [fde55bea2c3d62c8fec2d18fdebc263e6486150f] Include XEP-0172 nick in all outgoing presence subscribe stanzas
git bisect skip fde55bea2c3d62c8fec2d18fdebc263e6486150f
# skip: [dcfc0d50f4b8cf497866e5f0b6824094dd6aa9d1] Refactor shared API functions out into `src/headless/shared/api`
git bisect skip dcfc0d50f4b8cf497866e5f0b6824094dd6aa9d1
# good: [447fe8ba0892319a27cc1cb0480867185a167cd5] Refactor the code related to storing SCRAM keys
git bisect good 447fe8ba0892319a27cc1cb0480867185a167cd5
# skip: [48e7987f38058dc40a98e7afd8e37c89cb92e4b2] Start work on removing constants from _converse object
git bisect skip 48e7987f38058dc40a98e7afd8e37c89cb92e4b2
# skip: [5c3acc8a4d33173183b492382d623b578fb75136] Rename package `module` files to `index.js`
git bisect skip 5c3acc8a4d33173183b492382d623b578fb75136
# good: [89d231a5dd9af1240d81d01746663ff757a05db3] Translated using Weblate (Chinese (Simplified))
git bisect good 89d231a5dd9af1240d81d01746663ff757a05db3
# good: [89d231a5dd9af1240d81d01746663ff757a05db3] Translated using Weblate (Chinese (Simplified))
git bisect good 89d231a5dd9af1240d81d01746663ff757a05db3
# skip: [cdda140137625e584d20545f72d6b926b5d4af06] Bump webpack from 5.75.0 to 5.76.0 (#3173)
git bisect skip cdda140137625e584d20545f72d6b926b5d4af06
# skip: [f91f4cb7abcd4f5f89081c40226e6838c3fc48ff] Allow arguments to be passed when running tests
git bisect skip f91f4cb7abcd4f5f89081c40226e6838c3fc48ff
# good: [6e71555ee4599300b42d683ba33e010b095e4816] Release 10.1.4
git bisect good 6e71555ee4599300b42d683ba33e010b095e4816
# bad: [12a7933e390b8b9392a2837f9cc07d3fff6ffbbd] Fix GIF rendering artifacts related to patching
git bisect bad 12a7933e390b8b9392a2837f9cc07d3fff6ffbbd
# good: [5e02b9bd5d1a40f68a9650a1536c042c7b7b4967] Release 10.1.5 (this time hopefully for real)
git bisect good 5e02b9bd5d1a40f68a9650a1536c042c7b7b4967
# bad: [d1962d0b34b098bd0c4c8fefeb3d66d63f62056b] Use relative imports in headless
git bisect bad d1962d0b34b098bd0c4c8fefeb3d66d63f62056b
# bad: [521d3ae9eafb4c98fedeb716e0c17ade0d001f39] Set `main` attribute in `package.json`
git bisect bad 521d3ae9eafb4c98fedeb716e0c17ade0d001f39
# good: [c30569dfd3ce493020847be21ea5301a3c0acd7e] Release 10.1.5
git bisect good c30569dfd3ce493020847be21ea5301a3c0acd7e
# good: [e31d4c7bac745d7dffa989b5e45a570dcb0185b2] Release 10.1.5
git bisect good e31d4c7bac745d7dffa989b5e45a570dcb0185b2
# first bad commit: [521d3ae9eafb4c98fedeb716e0c17ade0d001f39] Set `main` attribute in `package.json`
```
```

**Comment by jcbrand** [comment]
Thanks for the feedback everyone and sorry for the wait. I believe it's fixed now.

**Comment by licaon-kter** [comment]
It starts now :)
