### ISSUE TITLE
Can't access lexical declaration 'init_settings' before initialization

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#3348]
HEAD (d4dfc3785b962973c8e17de9fa8f3ee7204329bc) is bad, I see just the background

```
Uncaught ReferenceError: Cannot access 'init_settings' before initialization
    at getInitSettings (utils.js:33:5)
    at isTestEnv (session.js:18:12)
    at Object.get (_converse.js:70:22)
    at new ConversePrivateGlobal (_converse.js:78:15)
    at 3407 (_converse.js:188:19)
    at __webpack_require__ (bootstrap:19:1)
    at Object.load (entry.js:62:9)
    at Object.initialize (entry.js:31:25)
    at chat/:2:116
getInitSettings	@	utils.js:33
isTestEnv	@	session.js:18
get	@	_converse.js:70
ConversePrivateGlobal	@	_converse.js:78
3407	@	_converse.js:188
__webpack_require__	@	bootstrap:19
load	@	entry.js:62
initialize	@	entry.js:31
(anonymous)	@	chat/:2
```
last known good for me was 04c37537dd7615d0a2a7d72b4b85f95a19275f5f

so bisect said:
```
ccc9d7ec4d4b30049a02b6b1c9f4bde14d9ab73e is the first bad commit
commit ccc9d7ec4d4b30049a02b6b1c9f4bde14d9ab73e
Author: JC Brand <jc@opkode.com>
Date:   Wed Mar 13 10:33:12 2024 +0200

    Include type declarations in NPM package

 package-lock.json                | 4 ++--
 package.json                     | 4 +++-
 src/headless/package.json        | 3 ++-
 src/types/shared/chat/utils.d.ts | 3 ++-
 4 files changed, 9 insertions(+), 5 deletions(-)
```

**Comment by jcbrand** [comment]
Can you please check again?

**Comment by licaon-kter** [comment]
tested HEAD (7ccc0fcbb412d4ced2fbd4a68a7cc54908bdd399), I still see just the background

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'animate')
    at object_merge (converse-headless.js:31353:12)
    at extendAppSettings (converse-headless.js:31402:3)
    at Object.extend (converse-headless.js:31486:12)
    at Object.initialize (index.js:25:22)
    at PluginSocket.initializePlugin (pluggable.js:193:47)
    at pluggable.js:129:22
    at Array.forEach (<anonymous>)
    at PluginSocket.loadPluginDependencies (pluggable.js:121:30)
    at PluginSocket.initializePlugin (pluggable.js:189:22)
    at pluggable.js:129:22
```

**Comment by jcbrand** [comment]
Can you please try again?

**Comment by licaon-kter** [comment]
7c75eb36a30188fc0c9dcabff36d0925591b689f is fixed, thanks
