### ISSUE TITLE
Registration form is not fetched in latest version 10.1.7

### ISSUE THREAD

**Issue by SPiRiT369** [conversejs/converse.js#3386]
**Describe the bug**
On latest version (10.1.7) - registration forms are not fetched so users can't register.
This doesn't happen in earlier version (10.1.6).

**To Reproduce**
You can see it in https://inverse.chat/#converse/register (for example).
Type xmpp provider and click "Fetch registration form".
Also happens to me in my server.

**Expected behavior**
A registration form should be displayed.

Browser console shows:
```
panel.js:96 Uncaught TypeError: n._proto._reqToData is not a function
    at a_.getRegistrationFields (panel.js:96:34)
    at e._connect_cb (panel.js:80:29)
    at _o._onInitialMessage (websocket.js:270:24)
    at socket.onmessage (websocket.js:170:51)
getRegistrationFields	@	panel.js:96
e._connect_cb	@	panel.js:80
```

**Comment by tigransimonyan** [comment]
wow, this problem is not solved yet.

**Comment by member7me** [comment]
Not fixed in 10.1.8.
