### ISSUE TITLE
Conversejs shows contact as online but openfire shows as offline in sessions

### ISSUE THREAD

**Issue by sergiobaiao** [conversejs/converse.js#3470]
**Describe the bug**
Converse.js shows contact as online but openfire shows as offline in sessions. Every user on Converse.js appears to be offline, now message is delivered. 

**To Reproduce**
1. Using Openfire v4.8.3 and Converse.js v10.1.7 with the following initialization:
```
   converse.initialize({
        authentication: 'login',
        auto_reconnect: true,
        discover_connection_methods: false,
        bosh_service_url: 'http://chat.pgepi.lan:7070/http-bind',
        message_archiving: 'always',
        allow_adhoc_commands: false,
        allow_contact_removal: false,
        allow_non_roster_messaging: true,
        auto_register_muc_nickname: true,
        auto_join_on_invite: true,
        auto_subscribe: true,
        default_domain: 'pgepi.lan',
        domain_placeholder: 'pgepi.lan',
        i18n: 'pt_BR',
        language: 'pt_BR',
        locked_domain: true,
        loglevel: 'debug',
        muc_domain: 'pgepi.lan',
        registration_domain: 'pgepi.lan',
        show_controlbox_by_default: true,
        view_mode: 'fullscreen',
        hide_offline_users: false
    });
```
3. Open two different browsers with two different users
4. Add and text each other. 
5. See error. No message is delivered.
6. On the browser console, this is shown at every login and when i try to change status:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at generateVerificationString (utils.js:24:36)
    at createCapsNode (utils.js:33:22)
    at addCapsNode (utils.js:43:27)
    at Object.callback (index.js:18:56)
    at events.js:59:58
    at async XMPPStatus.constructPresence (status.js:88:20)
    at async Object.send (presence.js:25:30)`

**Comment by SPiRiT369** [comment]
I'm just a visitor here 🤗 Saw that you set locked_domain to true, but I think you should set your domain there instead.
And about the user status issue, I always have this problem with xmpp, also when using Gajim/Conversation, there is a mix of statuses 😩 Annoying indeed.

**Comment by jcbrand** [comment]
@sergiobaiao Could you please check whether the problem persists with Converse 11.0.0?
